
vars:
    asd: 123

httpServers:
    -   name: 'server'
        ports:
            http: 8000
            https: 8001
        routers:

            -   name: 'webapps'
                description: 'Webapps Router'
                path: '/'
                routes:

                    # Demo service
                    -   method: 'GET'
                        path: '/'
                        pipeline:
                            -   staticsPath: '$demo-webapp'

            -   name: 'api'
                description: 'API Router'
                path: '/api'
                routes:

                    # Demo service
                    -   method: 'GET'
                        path: '/demo'
                        pipeline:
                            -   handler: '$demo-handler'